"""
P&ID Engineering Knowledge Base
Based on ISA-5.1 Standard and industry best practices.
"""

PID_ENGINEERING_KNOWLEDGE = {
    # ISA-5.1 Standard Instrument Identification Letters
    "instrument_first_letters": {
        "A": {"variable": "Analysis", "description": "Composition, pH, conductivity, oxygen"},
        "B": {"variable": "Burner/Combustion", "description": "Flame detection"},
        "C": {"variable": "User Choice", "description": "Typically conductivity"},
        "D": {"variable": "Density", "description": "Density or specific gravity"},
        "E": {"variable": "Voltage", "description": "Electrical voltage"},
        "F": {"variable": "Flow", "description": "Flow rate"},
        "G": {"variable": "Gauging", "description": "Position, length"},
        "H": {"variable": "Hand", "description": "Manual operation"},
        "I": {"variable": "Current", "description": "Electrical current"},
        "J": {"variable": "Power", "description": "Electrical power"},
        "K": {"variable": "Time", "description": "Time, schedule"},
        "L": {"variable": "Level", "description": "Liquid level"},
        "M": {"variable": "Moisture", "description": "Moisture or humidity"},
        "N": {"variable": "User Choice", "description": "User defined"},
        "O": {"variable": "User Choice", "description": "User defined"},
        "P": {"variable": "Pressure", "description": "Pressure or vacuum"},
        "Q": {"variable": "Quantity", "description": "Totalize, event"},
        "R": {"variable": "Radiation", "description": "Nuclear radiation"},
        "S": {"variable": "Speed", "description": "Speed, frequency"},
        "T": {"variable": "Temperature", "description": "Temperature"},
        "U": {"variable": "Multivariable", "description": "Multiple variables"},
        "V": {"variable": "Vibration", "description": "Vibration"},
        "W": {"variable": "Weight", "description": "Weight or force"},
        "X": {"variable": "Unclassified", "description": "Unclassified, H2S, LEL detectors"},
        "Y": {"variable": "Event", "description": "Event, state"},
        "Z": {"variable": "Position", "description": "Position, dimension"},
    },
    "instrument_succeeding_letters": {
        "A": "Alarm",
        "C": "Controller",
        "D": "Differential",
        "E": "Element/Sensor",
        "F": "Ratio",
        "G": "Glass/Gauge",
        "H": "High",
        "I": "Indicator",
        "K": "Control Station",
        "L": "Low",
        "M": "Middle",
        "O": "Orifice",
        "P": "Point",
        "Q": "Integrate/Totalize",
        "R": "Recorder",
        "S": "Switch",
        "T": "Transmitter",
        "U": "Multifunction",
        "V": "Valve",
        "W": "Well/Probe",
        "Y": "Relay/Compute",
        "Z": "Safety/Emergency",
    },
    "valve_types": {
        "gate": {
            "symbol": "Two triangles meeting at points",
            "application": "On/off service, full bore",
        },
        "globe": {
            "symbol": "Circle between two triangles",
            "application": "Throttling service",
        },
        "ball": {
            "symbol": "Filled circle between triangles",
            "application": "Quick on/off, tight shutoff",
        },
        "plug": {
            "symbol": "Rectangle between triangles",
            "application": "On/off and throttling",
        },
        "butterfly": {
            "symbol": "Triangles with vertical line",
            "application": "Large flow, low pressure drop",
        },
        "check": {
            "symbol": "Triangle with bar pointing in flow direction",
            "application": "Prevent backflow",
        },
        "relief": {
            "symbol": "Angle body with spring symbol",
            "application": "Overpressure protection",
        },
        "control": {
            "symbol": "Globe valve with diaphragm actuator",
            "application": "Automatic control",
        },
        "motor_operated": {
            "symbol": "Valve with M in circle",
            "application": "Remote operation (MOV)",
        },
        "solenoid": {
            "symbol": "Valve with coil symbol",
            "application": "Quick electric actuation",
        },
    },
    "valve_positions": {
        "NC": "Normally Closed",
        "NO": "Normally Open",
        "LC": "Locked Closed",
        "LO": "Locked Open",
        "FC": "Fail Closed",
        "FO": "Fail Open",
        "FL": "Fail Last",
        "CSC": "Car Sealed Closed",
        "CSO": "Car Sealed Open",
        "TSO": "Tight Shut Off",
    },
    "service_codes": {
        "P": "Process",
        "BD": "Blowdown",
        "RL": "Relief",
        "FL": "Flare",
        "FG": "Fuel Gas",
        "IA": "Instrument Air",
        "PA": "Plant Air",
        "N2": "Nitrogen",
        "ST": "Steam",
        "CW": "Cooling Water",
        "BW": "Boiler Water",
        "FW": "Firewater",
        "UW": "Utility Water",
        "OW": "Oily Water",
        "CD": "Condensate",
        "DR": "Drain",
    },
    "area_classification": {
        "Class I": "Flammable gases, vapors, or liquids",
        "Class II": "Combustible dust",
        "Class III": "Ignitable fibers",
        "Division 1": "Hazardous atmosphere during normal operation",
        "Division 2": "Hazardous only under abnormal conditions",
        "Zone 0": "Explosive atmosphere continuously present",
        "Zone 1": "Explosive atmosphere likely during normal operation",
        "Zone 2": "Explosive atmosphere unlikely, short duration",
    },
}
